### ISSUE TITLE
"Show All Project Symbols" does not show "Base Application" and "System Application" objects if app uses the "application" property to declare these dependencies

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#134]
Hi @anzwdev,
I noticed that the AL Object Browser does not show the "Base Application" and "System Application" objects (and "Application" objects, if any) if the app in the project folder uses the "application" property to declare these dependencies.

Also, another point, it might be interesting to check if the symbols of the dependencies of a dependency with `"propagateDependencies": true` could also be shown in the Object browser.

**Comment by anzwdev** [comment]
Hi
You are right, all these cases should be supported, I'll add it.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it fixes this issue.

**Comment by rvanbekkum** [comment]
Hi @anzwdev,
Thanks. I've tested it, but unfortunately I still don't get to see the "Base Application" dependency (for an app that uses the "application" property):
![show-project-symbols](https://user-images.githubusercontent.com/7383241/85997736-29167b80-ba0a-11ea-83b2-e5224c282636.png)

**Comment by anzwdev** [comment]
Which files do you have in your .alpackages folder? It works for me, so there must be a difference somewhere between yours and mine projects.

**Comment by rvanbekkum** [comment]
I tried it again today without (knowingly) changing anything and now it works. Not sure if or what I did wrong (if I ever run into it again, I'll try to see what is causing the issue).
Anyway, it seems to work, so thanks for adding support for this 😃!

**Comment by rvanbekkum** [comment]
Hi, I ran into the same issue again, and I think it might be some kind of locking issue (so, not necessarily related to this issue #134).
The Base Application is not shown in the AL Object Browser when running "Show All Project Symbols", but when I run _Download Symbols_ again, then sometimes the Base Application symbols do show up, but sometimes they won't because of a lock on the .app file:
![image](https://user-images.githubusercontent.com/7383241/86530206-fd3a4080-beb6-11ea-9879-fb626e05ad7a.png)
I don't think this necessarily is an issue with your VSCode extension, because this locking issue is a known issue with AL Language extension that occasionally pops up.
