### ISSUE TITLE
Problems with AL Language: 6.x

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#181]
I have some problems with AL Language Extension: 6.x
I know that there is still some time to the release, but maybe the errors are helpful for a smoother update.
When I try to add Tooltips I receive the following error:

> Methode not found: "Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.CompilationUnitSyntax Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTree.GetCompilationUnitRoot()".

![image](https://user-images.githubusercontent.com/56249171/93453229-b49cfb80-f8d9-11ea-8de0-264653bf81e2.png)

ApplicationArea is inserted with the wrong keyword:
> MultiLine=All;
instead of `ApplicationArea=All;``

AL Language Version: 6.0,308593

**Comment by anzwdev** [comment]
Thank you for letting me know. I'll check what can be fixed now and what has to wait for the new AL Language extension release.

**Comment by anzwdev** [comment]
I've fixed these 2 issues in the last release of my extension. Version 6 of Microsoft AL Language extension is now available in the Visual Studio Marketplace, so I am testing if there are any other issues and will release a new version of my extension in the next few days.

**Comment by anzwdev** [comment]
I've updated background language server to work with the new version of BC and released a new version of the extension

**Comment by pri-kise** [comment]
I don't know if this is related but I now receiv the following error on removing the with usage.
![image](https://user-images.githubusercontent.com/56249171/96860845-90e24d80-1463-11eb-8626-de100da3e2c9.png)

> Methode nicht gefunden: "System.Collections.Immutable.ImmutableArray`1<Microsoft.Dynamics.Nav.CodeAnalysis.IParameterSymbol> Microsoft.Dynamics.Nav.CodeAnalysis.IMethodSymbol.get_Parameters()".

**Comment by DanielGoehler** [comment]
I have the same issue when I try the Action "Remove 'with' usage from the Active Project".

**Comment by anzwdev** [comment]
I've released a new version of the extension, it works for me now, could you check if it also works for you?

**Comment by DanielGoehler** [comment]
This still happens. Is there any way to get more details where this error comes from? <img width="1412" alt="Screenshot" src="https://user-images.githubusercontent.com/9556549/114094633-d634f300-98bc-11eb-9fcd-6977a2c4f613.png">

**Comment by anzwdev** [comment]
Are you using the latest version of the Microsoft AL Extension from the Visual Studio Marketplace or older one from there or from VSIX file?

**Comment by DanielGoehler** [comment]
I use the current one from Marketplace: v7.1.441584

**Comment by anzwdev** [comment]
It probably is a special case of AL code that I haven't tested and it breaks the logic. It would help me if you could try to find it. There is only one place in my code that could thow the error that you have, I've added a few additional checks around it and released a new version of the extension. Could you check if it works now?

**Comment by DanielGoehler** [comment]
Sure. Is there a place for addition information? Currently still the same error message
![image](https://user-images.githubusercontent.com/9556549/115229093-e6e23600-a112-11eb-965a-2e76c4af99ac.png)

**Comment by anzwdev** [comment]
No, there is no place for additional information.
There is just one place where IMethodSymbol.Parameters is called, I've added additional checks around it but it still breaks in your vs code. It looks like a problem with dynamic loading of .net libraries. I'll do a few more changes to the extension, I hope that it will help.

The code that breaks on your machine is used to detect function parameters where we should not add variable name at the front, i.e.:
```pascal
with p do begin
  SetRange("No.", "No.");
```
should be converted to:
```pascal
p.SetRange("No.", p."No.");
```

**Comment by DanielGoehler** [comment]
I think the problem occurs earlier. When I run this on an empty project (AL: Go!), I still get the error **Method not found Microsoft.Dynamics.Nav.CodeAnalysis.IMethodSymbol.get_Parameters()**. The question is, where does the **Microsoft.Dynamics.Nav.CodeAnalysis.dll** comes from? Do I need a local installation of Business Central, which I don't have? Or is this **dll** expected in the AL Language Extension and not found?

**Comment by anzwdev** [comment]
Microsoft.Dynamics.Nav.CodeAnalysis.dll is loaded from the bin folder of active Microsoft AL Extension. But it is really strange, because IMethodSymbol.get_Parameters() exists also in the old Microsoft.Dynamics.Nav.CodeAnalysis.dll from Nav 2018. It looks like a problem with loading dlls but I am not sure which one fails. Maybe it is a problem with System.Collections.Immutable.ImmutableArray class from System.Collections.Immutable.dll. When you want to write your own code analyzer you have to reference System.Collections.Immutable.dll version that is installed with Microsoft AL Extension, if you reference newer version of the library, your analyzer won't work. 

I need to run a few more tests, maybe you have newer version of this library in GAC and it is loaded instead of the one from Microsoft folder?

**Comment by DanielGoehler** [comment]
I tried to copied System.Collections.Immutable.dll from .vscode\extensions\ms-dynamics-smb.al-7.1.441584\bin\win32 to .vscode\extensions\andrzejzwierzchowski.al-code-outline-3.0.2\bin\netframework, but this results in the same error message.

I check [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and you're right, **AZALDevToolsServer.NetFramework.exe** has loaded both GAC System.Collections.Immutable.dll from GAC (4.700.19.56404) and from the Language Extension (4.6.26515.6) and the GAC Version is newer.
<img width="1489" alt="Screenshot" src="https://user-images.githubusercontent.com/9556549/116005413-15767a00-a607-11eb-9d37-06df2fba60d0.png">

My Setup is Windows 10 20H2 (Build 19042.928) with .NET Framework 4.8, but without .NET Framework 3.5. What is yours?

**Comment by anzwdev** [comment]
I have the same version of windows with .net framework 4.8, but I don't have System.Collections.Immutable.dll in GAC so it looks like this is what breaks it on your machine. I am lookin at the way of preventing loading GAC version now.

**Comment by anzwdev** [comment]
I've released a new version of the extension. It uses .net 5 instead of .net framework 4.8, I hope that it will solve your problem as GAC no longer exists in .net core/.net 5

**Comment by DanielGoehler** [comment]
Works perfect.
