### ISSUE TITLE
Cleanup action adds invalid "Rec." in SetLoadFields statement on page objects

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#348]
Scenario:

- I've table A with a field `"Sales Unit of Measure"`
- I've a page A (with source table A)  with a page field `Rec."Sales Unit of Measure"`

`field("Sales Unit of Measure"; Rec."Sales Unit of Measure")`

- The page has this action

```
 trigger OnAction()
var
    Item: Record Item;
begin
    if Rec."Item No." <> '' then begin
        Item.SetLoadFields("Sales Unit of Measure");
        if Item.Get(Rec."Item No.") then
            ReferenceUOMCode := Item."Sales Unit of Measure";
    end;
end;
```

Running the code cleanup incorrectly adds `Rec.` to the `Item.SetLoadFields` (probably because that field is both know on the page / sourcetable and the Item record). However, the `SetLoadsFields` should not be changed, as it should respect the context of the preceding `Item.` record and not the current `Rec`.

```
trigger OnAction()
var
    Item: Record Item;
begin
    if Rec."Item No." <> '' then begin
        Item.SetLoadFields(Rec."Sales Unit of Measure");  // << This is wrong and results in compile errors
        if Item.Get(Rec."Item No.") then
            ReferenceUOMCode := Item."Sales Unit of Measure";
    end;
end;

```

FYI, used these workspace settings

```
"alOutline.fixCodeCopMissingParenthesesOnSave": true,
        "alOutline.lockRemovedFieldsCaptions": true,
        "alOutline.addToolTipsToPageFields": true,
        "alOutline.codeCleanupActions": [
            "AddMissingParentheses",
            "AddObjectCaptions",
            "AddTableFieldCaptions",
            "AddToolTips",
            "AddPageFieldCaptions",
            "ConvertObjectIdsToNames",
            "FixIdentifiersCase",
            "FixKeywordsCase",
            "FormatDocument",
            "LockRemovedFieldCaptions",
            "RemoveBeginEnd",
            "RemoveUnusedVariables",
            "RemoveWithStatements",
            "SortPermissions",
            "SortPermissionSetList",
            "SortProperties",
            "SortVariables",
            "TrimTrailingWhitespace"
        ],
        "alOutline.defaultAddPageFieldCaptionsSettings": {
            "setActionGroupsCaptions": true,
            "setActionsCaptions": true,
            "setLabelsCaptions": true,
            "setPartsCaptions": false
        },
        "alOutline.defaultRemoveUnusedVariablesSettings": {
            "removeGlobalVariables": true,
            "removeLocalMethodParameters": true,
            "removeLocalVariables": true
        }
```

**Comment by anzwdev** [comment]
Hi

I tried to replicate your issue, but I was not able to do it. The only command that can add "Rec." to the code is "Remove with". I've modified it to fix your #346 issue, there is a chance that these fixes also fixed this problem. I've released a new version of the extension, could you check if it works now?

**Comment by fvet** [comment]
Hi @anzwdev , just checked with the latest v3.0.30 version but the problem still occurs. Maybe important to know is that I'm running the AL insider vsix, v**9.0**.592718. If needed I can try to create a small sample project?

**Comment by anzwdev** [comment]
Hi
That explains why it does not work for you. Current version of the extension has been compiled against the microsoft extension from visual studio marketplace. If I recompile it for the insider version of the vsix there is a risk that not everything will work for users using current version of Microsoft extension. I will release a new version as soon as version 9 of AL compiler is ready.

**Comment by anzwdev** [comment]
I've released a new version of the extension recompiled to work with the new AL compiler v9. Could you check if it solves your issue?

**Comment by fvet** [comment]
I'm still facing the same issue.

Retested with
- AL Language : v9.0.605172
- AZ AL Dev Tools/AL Code Outline: v3.0.31

Sample code (add a source table with a field `"Sales Unit of Measure"`.

```
page 71097464 "ESCU Test"
{
    PageType = Worksheet;
    SourceTable = "ESCU Unit Calculation";
    UsageCategory = None;

    layout
    {
        area(Content)
        {
            repeater(General)
            {
                field("Sales Unit of Measure"; Rec."Sales Unit of Measure")
                {
                    ApplicationArea = All;
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action("Reset")
            {
                ApplicationArea = All;

                trigger OnAction()
                var
                    Item: Record Item;
                begin
                    if Rec."Item No." <> '' then begin
                        Item.SetLoadFields("Sales Unit of Measure");
                    end;
                end;
            }
        }
    }
}

```

**Comment by fvet** [comment]
Hi @anzwdev,

Have you been able to simulate this? Facing the same on other objects to in combination with `Setrange`

**Comment by anzwdev** [comment]
Hi

No, I was trying to replicate the issue, but everything works fine for me. I will try to run it on different machines and with different projects, maybe it will break.

**Comment by fvet** [comment]
Seems like the issue no longer appears with the latest version.
