### ISSUE TITLE
Fields selection is not working anymode

### ISSUE THREAD

**Issue by mihaivalceaCPS** [anzwdev/al-code-outline#603]
Hi,

I cannot select and add fields to page. 
After I check a field in fields list the check mark si automatically disabled.

Regards,
Mihai

**Comment by barandeniz** [comment]
I am experiencing same issue also.

**Comment by pri-kise** [comment]
I found this in the VS Code repository: https://github.com/microsoft/vscode/issues/223363

**Comment by erikrijn** [comment]
Just to let you know, same issue here for the last couple of weeks.

**Comment by mihaivalceaCPS** [comment]
The issue still exists and maybe un update is required.

**Comment by anzwdev** [comment]
It is broken in the latest version of VS Code. I am checking if it is a bug or vs code api change.

**Comment by anzwdev** [comment]
The issue was caused by changes to the vs code api. One of the properties of pick list items that were ignored in the previous versions needs to be set now. I've released a new version of the extension, problem should be solved now.

**Comment by alan0z** [comment]
@anzwdev after update to v14.0.956192 (pre-release) still not works. Tested on PageExt and Pages. Still impossble to "check" the checkbox.
VSCode:
Version: 1.92.1 (system setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by dannoe** [comment]
@alan0z Try version 13.70.0 (non prerelease)

**Comment by pri-kise** [comment]
For me it isn't working with the latest version.
I installed the version v13.70.0 of the extension and closed all VS Code windows.

VS Code:
Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z

**Comment by sofiaagmp** [comment]
It also still isn't working on my end. Even with the latest version.

**Comment by alan0z** [comment]
> @alan0z Try version 13.70.0 (non prerelease)

The same result :(

**Comment by sofiaagmp** [comment]
> As a temporary workaround you can search for the following file:
> 
> ```
> C:\Users\<username>\.vscode\extensions\andrzejzwierzchowski.al-code-outline-13.70.0\out\codeactions\addFields\tableFieldsSelector.js
> ```
> 
> And comment out line 121:
> 
> ```js
> //this._quickPick.items = newItems;
> ```
> 
> The sorting after selected items isn't working with this, but at least it is usable. This change will be lost if you install a new version.

I tried this and still doesn't let me select anything.

**Comment by dannoe** [comment]
> 
> I tried this and still doesn't let me select anything.

Did you reload or restart vscode after changing the file?
Is your current active version of the al-code-outline extension 13.70.0?

**Comment by sofiaagmp** [comment]
> > I tried this and still doesn't let me select anything.
> 
> Did you reload or restart vscode after changing the file? Is your current active version of the al-code-outline extension 13.70.0?

Tried again and it is working. Thank you!

**Comment by anzwdev** [comment]
I've found what was wrong. The latest version of VS Code triggers quick pick events in a different way. New version is ready, it should work for you now.

**Comment by pri-kise** [comment]
I updated my VS Code today.

Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z

and now it's working again with version `v13.71.0`.
